[package]
name = "rusty_osu"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.1"
bytemuck = "1.23.1"
cpal = "0.16.0"
gl = "0.14.0"
glfw = "0.59.0"
rodio = "0.20.1"
symphonia = "0.5.4"

